version: 2
updates:
  # Enable version updates for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "ayutaz"
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "build"
      prefix-development: "build"
      include: "scope"

  # Enable version updates for npm packages in web-ui
  - package-ecosystem: "npm"
    directory: "/web-ui"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "ayutaz"
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "build"
      prefix-development: "build"
      include: "scope"
    groups:
      # Group all non-major updates together
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Enable updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "ayutaz"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"