run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - test/integration

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gosec
    - misspell
    - lll
    - nakedret
    - prealloc
    - gocritic
    - gochecknoinits
    - gocognit
    - godot
    - godox
    - goerr113
    - gofumpt
    - gomodguard
    - goprintffuncname
    - makezero
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - predeclared
    - revive
    - stylecheck
    - thelper
    - unconvert
    - unparam
    - whitespace

  disable:
    - exhaustive
    - exhaustruct
    - gochecknoglobals
    - gocyclo
    - funlen
    - goconst
    - testpackage
    - wrapcheck
    - wsl
    - nlreturn
    - paralleltest
    - tparallel
    - ifshort
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    - goheader
    - tagliatelle
    - promlinter
    - importas
    - exportloopref
    - gomnd

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/ayutaz/orochi
  golint:
    min-confidence: 0.8
  govet:
    check-shadowing: true
  lll:
    line-length: 120
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  godot:
    scope: declarations
    capital: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst