linters-settings:
  errcheck:
    # Report about assignment of errors to blank identifiers
    check-blank: false

linters:
  enable:
    - errcheck
    - govet
    - godot
    - gofmt
    - gocritic
    - gosimple
    - ineffassign
    - lll
    - noctx
    - unparam
    - revive
  disable:
    - godox

issues:
  exclude-rules:
    # Exclude errcheck for _ = writeJSON pattern
    - path: internal/web/api.go
      linters:
        - errcheck
      text: "Error return value is not checked"