linters-settings:
  errcheck:
    # Report about assignment of errors to blank identifiers
    check-blank: false
  gosec:
    # Exclude specific rules if needed
    excludes:
      - G104  # Unhandled errors (covered by errcheck)
      - G304  # File path provided as taint input (we handle user input carefully)
  lll:
    line-length: 120
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - commentedOutCode

linters:
  enable:
    - errcheck
    - govet
    - godot
    - gofmt
    - gocritic
    - gosimple
    - ineffassign
    - lll
    - noctx
    - unparam
    - revive
    - gosec
    - staticcheck
    - typecheck
    - unused
  disable:
    - godox

issues:
  exclude-rules:
    # Exclude errcheck for _ = writeJSON pattern
    - path: internal/web/api.go
      linters:
        - errcheck
      text: "Error return value is not checked"